package com.viewfunction.schedulerManagement.persistent.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;

import com.viewfunction.schedulerManagement.persistent.CalendarActionDataObject;
import com.viewfunction.schedulerManagement.persistent.CalendarEntity;

/**
 * Class _CalendarAction was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _CalendarAction extends CayenneDataObject {

    public static final String CALENDAR_ACTION_NAME_PROPERTY = "calendarActionName";
    public static final String CALENDAR_ACTION_TYPE_PROPERTY = "calendarActionType";
    public static final String CALENDAR_ACTION_DATA_LIST_PROPERTY = "calendarActionDataList";
    public static final String CALENDAR_ENTITY_PROPERTY = "calendarEntity";

    public static final String CALENDAR_ACTION_ID_PK_COLUMN = "calendarActionId";

    public void setCalendarActionName(String calendarActionName) {
        writeProperty("calendarActionName", calendarActionName);
    }
    public String getCalendarActionName() {
        return (String)readProperty("calendarActionName");
    }

    public void setCalendarActionType(String calendarActionType) {
        writeProperty("calendarActionType", calendarActionType);
    }
    public String getCalendarActionType() {
        return (String)readProperty("calendarActionType");
    }

    public void addToCalendarActionDataList(CalendarActionDataObject obj) {
        addToManyTarget("calendarActionDataList", obj, true);
    }
    public void removeFromCalendarActionDataList(CalendarActionDataObject obj) {
        removeToManyTarget("calendarActionDataList", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<CalendarActionDataObject> getCalendarActionDataList() {
        return (List<CalendarActionDataObject>)readProperty("calendarActionDataList");
    }


    public void setCalendarEntity(CalendarEntity calendarEntity) {
        setToOneTarget("calendarEntity", calendarEntity, true);
    }

    public CalendarEntity getCalendarEntity() {
        return (CalendarEntity)readProperty("calendarEntity");
    }


}
